Option Explicit

Sub InsertBOM_MultipleSheets()

    Dim swApp As SldWorks.SldWorks
    Dim swModel As SldWorks.ModelDoc2
    Dim swDraw As SldWorks.DrawingDoc
    Dim swView As SldWorks.View
    Dim swBOMTable As SldWorks.BomTableAnnotation
    Dim boolStatus As Boolean

    Set swApp = Application.SldWorks
    Set swModel = swApp.ActiveDoc

    If swModel Is Nothing Or swModel.GetType <> swDocDRAWING Then
        MsgBox "Please open a drawing document."
        Exit Sub
    End If

    Set swDraw = swModel

    ' === Sheet 1 - Top Level Only ===
    boolStatus = swDraw.ActivateSheet("Sheet1")
    Set swView = swDraw.GetFirstView
    Set swView = swView.GetNextView

    If Not swView Is Nothing Then
        Set swBOMTable = swView.InsertBomTable4( _
            False, 0.2, 0.2, _
            swBOMConfigurationAnchorType_e.swBOMConfigurationAnchor_TopLeft, _
            swBomType_e.swBomType_TopLevelOnly, _
            "EPP", _
            "C:\PDM\ArrayVault1\Standards\Templates\BOMs\Top Level BOM.sldbomtbt", _
            False, 0, False)
    End If

    ' === Sheet 2 - Parts Only ===
    boolStatus = swDraw.ActivateSheet("Sheet2")
    Set swView = swDraw.GetFirstView
    Set swView = swView.GetNextView

    If Not swView Is Nothing Then
        Set swBOMTable = swView.InsertBomTable4( _
            False, 0.2, 0.2, _
            swBOMConfigurationAnchorType_e.swBOMConfigurationAnchor_TopLeft, _
            swBomType_e.swBomType_PartsOnly, _
            "Default", _
            "C:\PDM\ArrayVault1\Standards\Templates\BOMs\Product Table - POG.sldbomtbt", _
            False, 0, False)
    End If

    ' === Sheet 3 - Indented ===
    boolStatus = swDraw.ActivateSheet("Sheet3")
    Set swView = swDraw.GetFirstView
    Set swView = swView.GetNextView

    If Not swView Is Nothing Then
        Set swBOMTable = swView.InsertBomTable4( _
            False, 0.2, 0.2, _
            swBOMConfigurationAnchorType_e.swBOMConfigurationAnchor_TopLeft, _
            swBomType_e.swBomType_Indented, _
            "EPP", _
            "C:\PDM\ArrayVault1\Standards\Templates\BOMs\Page 3 BOM.sldbomtbt", _
            False, 0, False)
    End If

    MsgBox "? BOMs inserted for all three sheets!"

End Sub


